defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
account: rrg-bengioy-ad
timeout_min: 30
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
signal_delay_s: 600
max_num_timeout: 20
additional_parameters: {}
setup: []
mem_gb: 32
gres: gpu:1
cpus_per_task: 8
array_parallelism: 24
