defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 5760 # 96 hours
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
comment: null
exclude: null
signal_delay_s: 60
max_num_timeout: 0
additional_parameters: {}
setup: []
gres: gpu:1
mem_gb: 16
cpus_per_task: 4
partition: gpu_h100