pgd:
  name: pgd
  type: continuous
  placement: suffix
  generate_completions: all
  num_steps: 100
  seed: 0
  batch_size: 16
  optim_str_init: "x x x x x x x x x x x x x x x x x x x x" # all tested tokenizers convert this to exactly 20 tokens
  epsilon: 100000.
  alpha: 0.001
  max_new_tokens: 256
  embedding_scale: null
pgd_one_hot:
  name: pgd_one_hot
  type: continuous
  placement: suffix
  generate_completions: all
  num_steps: 100
  seed: 0
  batch_size: 2
  optim_str_init: "x x x x x x x x x x x x x x x x x x x x" # all tested tokenizers convert this to exactly 20 tokens
  epsilon: 100000.
  momentum: 0.5
  alpha: 0.001
  max_new_tokens: 256
ample_gcg:
  name: ample_gcg
  type: discrete
  placement: suffix
  generate_completions: all
  seed: 0
  prompter_lm:
    id: osunlp/AmpleGCG-llama2-sourced-llama2-7b-chat
    tokenizer_id: osunlp/AmpleGCG-llama2-sourced-llama2-7b-chat
    chat_template: null
    short_name: ample_gcg
    developer_name: osunlp
    batch_size: 2
    dtype: bfloat16
    attn_implmentation: null
    trust_remote_code: True
    compile: True
    generation_config:
      num_return_sequences: 200 # number of tries per prompt
      num_beams: 200
      num_beam_groups: 200
      do_sample: false
      max_new_tokens: 20 # attack length
      min_new_tokens: 20
      diversity_penalty: 1.0
  target_lm:
    batch_size: 24
    max_new_tokens: 256
gcg:
  name: gcg
  type: discrete
  placement: suffix
  generate_completions: all
  num_steps: 250
  seed: 0
  batch_size: 512
  optim_str_init: "x x x x x x x x x x x x x x x x x x x x" # all tested tokenizers convert this to exactly 20 tokens
  search_width: 512
  topk: 256
  n_replace: 1
  buffer_size: 0
  use_mellowmax: False
  use_constrained_gradient: False
  mellowmax_alpha: 1.0
  early_stop: False
  use_prefix_cache: True
  allow_non_ascii: False
  filter_ids: True
  add_space_before_target: False
  verbosity: WARNING
  max_new_tokens: 256
autodan:
  name: autodan
  type: discrete
  placement: prefix
  generate_completions: all
  num_steps: 100
  seed: 0
  batch_size: 64
  forward_batch_size: null
  eval_steps: 5
  num_elites: 0.05
  crossover: 0.5
  num_points: 5
  mutation: 0.01
  mutate_model:
    id: null
    tokenizer_id: null
    short_name: null
    developer_name: null
    chat_template: null
    dtype: bfloat16
    compile: false
    trust_remote_code: True
  max_new_tokens: 256
direct:
  name: direct
  type: discrete
  placement: null
  generate_completions: all
  num_steps: 1
  seed: 0
  batch_size: 4
  max_new_tokens: 256
pair:
  name: pair
  type: discrete
  placement: multi-turn
  generate_completions: all
  num_streams: 1
  keep_last_num: 3
  seed: 0
  num_steps: 20
  attack_model:
    id: lmsys/vicuna-13b-v1.5
    tokenizer_id: lmsys/vicuna-13b-v1.5
    dtype: bfloat16
    compile: false
    trust_remote_code: True
    short_name: vicuna
    developer_name: lmsys
    max_attempts: 5
    max_new_tokens: 512
    temperature: 1
    chat_template: vicuna
    top_p: 0.9
  target_model:
    max_new_tokens: 256
    temperature: 0
    top_p: 1
  judge_model:
    id: cais/HarmBench-Llama-2-13b-cls
    max_new_tokens: 1
human_jailbreaks:
  name: human_jailbreaks
  type: discrete
  placement: prompt
  generate_completions: all
  num_steps: 1
  seed: 0
  batch_size: 1
  max_new_tokens: 256
