defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  - paths
  # - override hydra/launcher: a100h100.yaml
  - _self_

hydra:
  # mode: MULTIRUN
  sweeper:
    params:
      datasets.rf_test.idx: "range(0,160,step=10)"
  run:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

generation_config:
  temperature: 0.0
  top_p: 1.0
  top_k: 0
  max_new_tokens: 256
  num_return_sequences: 1

attacks:
  gcg:
    num_steps: 300

datasets:
  rf_test:
    batch: 10
    path: ${oc.env:HOME}/harmful-harmless-eval/

_gcg_models:
  - ${models.${model}.id}
  - ${models.${model}.tokenizer_id}

_pair_models:
  - ${models.${model}.id}
  - ${models.${model}.tokenizer_id}
  - lmsys/vicuna-13b-v1.5
  - cais/HarmBench-Llama-2-13b-cls

# automatically select models based on attack
slurm_copy_hf_cache:
  models: ${oc.select:_${attack}_models,${_gcg_models}}

name: ${model}
save_dir: ${root_dir}/outputs/rf_test/v3/${name}/${attack}/results/
embed_dir: ${root_dir}/outputs/rf_test/v3/${name}/${attack}/embeddings/
overwrite: false
save_format: noDB
use_database: false

classifiers: ["strong_reject"]

# overrides for parallelism
attack: gcg
dataset: rf_test
model: redflag-tokens/llama3-2-rf-v3
# model: redflag-tokens/llama3-2-rf-AT-single-morekl-rampup
